include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/lib_backup_gold_20260929/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    deprecated_member_use: ignore

linter:
  rules:
    prefer_const_constructors: false
