workflows:
  android-workflow:
    name: Build APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      java: 17
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches
    scripts:
      - name: Create .env file
        script: |
          echo "$ENV_FILE" > $CM_BUILD_DIR/.env
      - name: Create google-services.json
        script: |
          echo "$GOOGLE_SERVICES_JSON" > $CM_BUILD_DIR/android/app/google-services.json
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - sly188217@gmail.com
        notify:
          success: true
          failure: true
